-- AlterTable: add auto-enrich + any other Settings columns missing in older Neon DBs
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "autoEnrich" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "autoDelete" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "deleteThreshold" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "searchOnlyMode" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "searchConfigJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxSearchesPerHour" INTEGER NOT NULL DEFAULT 6;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxSearchesPerDay" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "minDelayBetweenSearchesMinutes" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxKeywordsPerCycle" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxCommentsPerHour" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxCommentsPerWeek" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "proxyHost" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "proxyPort" INTEGER;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "proxyUser" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "proxyPass" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "lastHeartbeat" TIMESTAMP(3);
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "extensionStatus" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "platformUrl" TEXT NOT NULL DEFAULT '';

ALTER TABLE "SavedPost" ADD COLUMN IF NOT EXISTS "canonicalUrn" TEXT;
ALTER TABLE "SavedPost" ADD COLUMN IF NOT EXISTS "engagementScore" INTEGER;
